// ==========================================
// JAVASCRIPT OBJECTS
// ==========================================

/*
THEORY OVERVIEW:
Objects are the most important concept in JavaScript. They allow us to store 
collections of data and more complex entities in a structured "key-value" pair format.
Mastering objects is essential for both frontend and backend development.
*/

// ---------------------------------------------------------
// 1. OBJECT CREATION & CRUD OPERATIONS (Create, Read, Update, Delete)
// ---------------------------------------------------------

// CREATE: Defining an object
const user = {
    name: "Rohit",
    age: 20,
    email: "negi@gmail.com",
    amount: 3400
};

// READ: Accessing object properties
console.log("Name:", user.name); // Using dot notation
console.log("Age:", user.age);

// UPDATE & INSERT: 
// If the key exists, it updates the value. If not, it creates a new property.
user.amount = 5000; // Update existing property
user.aadhar = "1234"; // Insert new property

// DELETE: Removing a property from an object
delete user.email;

console.log("User after CRUD operations:", user);


// ---------------------------------------------------------
// 2. BEHIND THE SCENES: KEYS ARE STRINGS
// ---------------------------------------------------------

/*
Internally, JavaScript stores all object keys as Strings (unless they are Symbols).
We can access them using bracket notation, which is exactly how arrays work under the hood.
*/

// Bracket notation (Requires the key to be passed as a string)
console.log("Accessing name via bracket notation:", user["name"]);

// Why use bracket notation?
// It allows us to use keys that have spaces or special characters, which dot notation cannot handle.
user["home address"] = "Dwarka";
console.log("Home Address:", user["home address"]);


// ---------------------------------------------------------
// 3. OBJECT REFERENCES & COPYING (Shallow vs Deep)
// ---------------------------------------------------------

const user2 = user; 
// This DOES NOT create a new object. user2 and user point to the SAME memory reference in the Heap.
user2.age = 90;
console.log("Original user age changed due to reference:", user.age); // Outputs 90

// --- Shallow Copy (Using Spread Operator) ---
// Creates an independent copy for top-level properties.
const independentUser = { ...user };
independentUser.name = "Mohan";
console.log("Independent copy name:", independentUser.name); // Mohan
console.log("Original copy name remains:", user.name); // Rohit

/*
Limitation of Spread Operator: 
It only creates a "Shallow Copy". If the object contains nested objects, 
the nested objects still share the same reference.
*/

// --- Deep Copy (Using structuredClone) ---
// Creates a completely independent copy, including all nested objects.
const deepCopiedUser = structuredClone(user);


// ---------------------------------------------------------
// 4. EXTRACTING KEYS, VALUES, AND ENTRIES
// ---------------------------------------------------------

// Object.keys() returns an array of all keys
const keysArray = Object.keys(user);
console.log("Keys:", keysArray);

// Object.values() returns an array of all values
const valuesArray = Object.values(user);
console.log("Values:", valuesArray);

// Object.entries() returns an array of arrays [key, value]
const entriesArray = Object.entries(user);
console.log("Entries:", entriesArray);


// ---------------------------------------------------------
// 5. ITERATING OVER OBJECTS (LOOPS)
// ---------------------------------------------------------

// Using for...in loop (Iterates over keys)
// Note: This is generally not the recommended way for objects due to prototype chain issues.
for (let key in user) {
    // We must use bracket notation here because 'key' is a variable holding a string
    console.log(`Key: ${key}, Value: ${user[key]}`); 
}

// Using for...of loop (Recommended)
// You cannot use for...of directly on an object because objects are not iterable.
// You must use it on the arrays generated by Object.keys(), Object.values(), or Object.entries().
console.log("--- Iterating with for...of ---");
for (let key of Object.keys(user)) {
    console.log(key, user[key]);
}

// Iterating over entries with destructuring
for (let [key, value] of Object.entries(user)) {
    console.log(`Destructured -> ${key}: ${value}`);
}


// ---------------------------------------------------------
// 6. DESTRUCTURING (Objects & Arrays)
// ---------------------------------------------------------

// Extracting specific properties into standalone variables
const { name, amount } = user;
console.log("Destructured Name:", name);

// Extracting and renaming variables
const { age: userAge } = user;
console.log("Renamed Destructured Age:", userAge);

// Array Destructuring
const arr = [10, 20, 30, 40];
const [first, second] = arr; // Gets 10 and 20
console.log("Array Destructuring:", first, second);


// ---------------------------------------------------------
// 7. OBJECT METHODS & THE 'this' KEYWORD
// ---------------------------------------------------------

/*
Objects can hold functions, which are called "methods".
The 'this' keyword inside a method refers to the object that called the method.
This prevents hardcoding variable names and makes the code reusable.
*/

const person = {
    name: "Rohit",
    greeting: function() {
        // 'this' refers to 'person' because person.greeting() is called.
        console.log(`Strike is coming on 18th October, ${this.name}`);
        return 20;
    }
};

const returnValue = person.greeting();
console.log("Returned from method:", returnValue);


// ---------------------------------------------------------
// 8. NESTED OBJECTS
// ---------------------------------------------------------

const student = {
    name: "Aman",
    address: {
        city: "Kotdwara",
        state: "Uttarakhand"
    }
};

console.log("Accessing nested object property:", student.address.city);


// ---------------------------------------------------------
// 9. ARRAYS ARE ACTUALLY OBJECTS
// ---------------------------------------------------------

/*
Behind the scenes, Arrays in JavaScript are just Objects where the keys are numeric indices (stored as strings).
[10, 20, 30] is stored as:
{
    "0": 10,
    "1": 20,
    "2": 30,
    "length": 3
}
*/
const mockArrayObj = {
    0: 10,
    1: 20
};
console.log("Accessing number key in object:", mockArrayObj[0]);


// ---------------------------------------------------------
// 10. SYMBOLS AS KEYS
// ---------------------------------------------------------

/*
Introduced in ES6 (2015), Symbols are guaranteed to be unique.
Object keys can only be Strings or Symbols.
Symbols are heavily used in library development to prevent naming collisions.
*/

const mySymbol = Symbol("id1");

const objWithSymbol = {
    [mySymbol]: "Hello Ji" // Bracket notation is required to use a Symbol as a key
};

console.log("Accessing Symbol Key:", objWithSymbol[mySymbol]);


// ==========================================
// INTERNAL ARCHITECTURE (MEMORY MANAGEMENT)
// ==========================================

/*
THEORY: HOW ARRAYS & OBJECTS ARE STORED IN MEMORY

1. Dynamic Size Problem in Arrays:
If an array stores different data types (strings, numbers), the bytes required per element fluctuate.
This breaks the formula: Base Address + (Index * Size) = Element Address.
Solution: Instead of storing actual values continuously, the array stores FIXED-SIZE Memory Addresses (Pointers).
- For small integers, the value itself might be encoded directly into the address block (using a special bit flag like ending in 0).
- For strings or complex objects, the array stores an 8-byte pointer that points to another location in the Heap where the actual string is stored.
This ensures O(1) access time because the array blocks remain a fixed size.

2. Array Push Memory Limits:
If an array runs out of contiguous memory space, JS finds a new, larger memory block, copies the data, and updates the "Element Pointer".
Because a constant array variable (const arr = []) only points to the "Map Pointer", updating the internal "Element Pointer" does not violate the 'const' assignment.

3. Object Storage Architecture:
Objects do not store data simply as continuous key-value arrays. If you update a value to a larger string, it would require shifting everything below it in memory.
Solution: JS Engines (like V8) use an architecture involving:
- Map Pointers (Hidden Classes): Stores the structure/shape of the object.
- Property Pointers: Points to the keys/values.
- Element Pointers: Points to numbered properties (like array indices).

Values and Keys (Strings) are stored elsewhere in the Heap, and the object's core structure only holds pointers (memory addresses) to them. This ensures consistency and prevents massive memory shifts when a string value is updated.

4. Optimization (Hash Maps):
If an object has 1000 properties, scanning them sequentially to find 'user.city' would be O(N).
Instead, JS engines implement Hash Maps internally. The key ("city") is hashed to generate a specific memory address, allowing the engine to fetch the property in O(1) constant time without checking every single property.
*/